# Site settings
title: 130lab
description: A GitHub Pages site for 130lab
# Theme settings
#theme: jekyll-theme-minimal
theme: jekyll-theme-cayman
# Build settings

markdown: kramdown
highlighter: rouge

collections:
  posts:
    output: true
    permalink: /blogs/:name