# Site settings
title: 130lab
description: A GitHub Pages site for 130lab
# Theme settings
theme: jekyll-theme-minimal
# Build settings

markdown: kramdown

collections:
  blogs:
    output: true
    permalink: /:collection/:year/:month/:day/:title/