# Site settings
title: 130lab
description: A GitHub Pages site for 130lab
# Theme settings
#theme: jekyll-theme-minimal
# Build settings
markdown: kramdown

categories: [130lab, default, tech, pcie, cxl]